version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
